image: openjdk:8-jdk-alpine

stages:
  - build
  - test
  - analysis
  - package
  - deploy

cache:
  paths:
    - .gradle

variables:
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"
  GIT_SUBMODULE_STRATEGY: normal
  GRADLE: ./gradlew -Pci --console=plain --no-daemon --max-workers=1 --stacktrace

assemble:
  stage: build
  script:
    - $GRADLE assemble
  artifacts: &artifacts
    paths:
      - build
      - 'subprojects/*/build'

test:
  stage: test
  script:
    - $GRADLE test
  needs:
    - assemble
  artifacts:
    <<: *artifacts
    reports:
      junit:
        - 'subprojects/*/build/test-results/$CI_JOB_NAME/TEST-*.xml'
  cache:
    policy: pull

lint:
  stage: test
  script:
    - $GRADLE ktlintCheck
  needs:
    - assemble
  cache:
    policy: pull

coverage:
  stage: analysis
  script:
    - $GRADLE rootTestCoverageReport
    - cat build/reports/jacoco/rootTestCoverageReport/html/index.html || true
  coverage: "/Total.*?([0-9]{1,3})%/"
  artifacts: *artifacts
  needs:
    - test

mavenSnapshot:
  stage: package
  script:
    - $GRADLE publish
  needs:
    - assemble
  cache:
    policy: pull

mavenRelease:
  stage: package
  script:
    - $GRADLE publishToMavenLocal
  tags: [ package ]
  only: [ tags ]
  needs:
    - assemble
  cache:
    policy: pull

pages:
  stage: package
  script:
    - $GRADLE gitlabPagesCreate
  only: [ tags ]
  needs:
    - coverage
  artifacts:
    paths:
      - public
  cache:
    policy: pull
