image: openjdk:8-jdk-alpine

stages:
  - build
  - test
  - analysis
  - package

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

variables:
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"
  GIT_SUBMODULE_STRATEGY: normal
  GRADLE: ./gradlew -Pci --console=plain --no-daemon --max-workers=1 --stacktrace

Build:
  stage: build
  script:
    - $GRADLE assemble
  artifacts:
    paths:
      - build

Test:
  stage: test
  script:
    - $GRADLE check
  artifacts:
    paths:
      - build
    reports:
      junit: build/test-results/test/TEST-*.xml

Coverage:
  stage: analysis
  script:
    - $GRADLE jacocoTestReport
    - cat build/jacocoHtml/index.html || true
  coverage: "/Total.*?([0-9]{1,3})%/"

Package:
  stage: package
  script:
    - $GRADLE publishToMavenLocal
  only: [ tags ]
  tags: [ package ]
